---
- name: "Deploy Influxdb"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_method: "ansible.builtin.sudo"

  tasks:

    - name: "Install Influxdb"
      when: inv_install_influxdb | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host__system_users: "{{ inv_prepare_host__influxdb_system_users }}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_influxdb_cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_influxdb_cert_bundles is defined
          vars:
            add_certificates__bundle_name: "{{ bundle.name }}"
            add_certificates__bundle_type: "{{ bundle.type }}"
            add_certificates__bundle_src: "{{ bundle.src }}"
            add_certificates__bundle_dest: "{{ bundle.dest }}"
            add_certificates__bundle_src_user: "{{ bundle.src_user }}"
            add_certificates__bundle_src_password: "{{ bundle.src_password }}"
            add_certificates__bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates__bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates__bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_influxdb"
          tags:
            - "labocbz.install_influxdb"
          vars:
            install_influxdb__http_bind_address: "{{ inv_install_influxdb__http_bind_address }}"
            install_influxdb__http_bind_port: "{{ inv_install_influxdb__http_bind_port }}"
            install_influxdb__ssl: "{{ inv_install_influxdb__ssl }}"
            install_influxdb__ssl_domain: "{{ inv_install_influxdb__ssl_domain }}"
            install_influxdb__ssl_key: "{{ inv_install_influxdb__ssl_key }}"
            install_influxdb__ssl_cert: "{{ inv_install_influxdb__ssl_cert }}"
          ansible.builtin.include_role:
            name: "labocbz.install_influxdb"

        - name: "Include labocbz.add_logrotate_confs"
          tags:
            - "labocbz.add_logrotate_confs"
          vars:
            add_logrotate_confs__files: "{{ inv_add_logrotate_confs__influxdb_configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_logrotate_confs"
